### ISSUE TITLE
Any way to get the Social Login profile picture, or Gravatar, WITHOUT a FullContact account?

### ISSUE THREAD

**Issue by advance512** [stormpath/stormpath-enrich#1]
The user logged in using Social Login.
His profile picture is *definitely* accessible. Is there no simple way, after the login (not in a Cronjob, enrich some time later on..), to get the URL of the profile image?

**Comment by rdegges** [comment]
That's not what this app is for -- this app just runs periodically to pull in additional information about an account, not something specific from a social provider.

The account object you have will have an access token property hanging off of it which you can post to the login provider (google, facebook, etc.) to get all the requested info you have. This is the proper way to do what you're asking.

**Comment by advance512** [comment]
I guess I'm just surprised Stormpath doesn't offer these kind of features out of the box, like:
https://auth0.com/docs/user-profile/normalized

Anyways, thanks for the answer.

**Comment by rdegges** [comment]
@advance512 these are included out of the box, however it depends on what info you request from the provider. For instance:

Let's say you just use our 'default' settings and log a user in with Facebook and don't request any custom scopes. What will happen is that we'll log the person in with minimal scope from facebook, pull down the user's scoped data (profile info), then store it in our 'providerData' store. Once you have the account object, if you look inside of the attached `providerData` resource you'll see all the stuff that was requested.

In your case, if you want to request other info from the provider, you need to tell the social login provider what you want via scopes, and then Stormpath will pull that data down for you automatically and dump it into `providerData`.

My answer before was assuming that you didn't request this scoped data during the login, which is why you'd have to make a separate call to get that info.

If you know what you want in advance, then just request that scoped data initially and pull it out of `providerData`.

This stuff is explained in detail (with examples) in our social authentication docs: https://docs.stormpath.com/rest/product-guide/latest/auth_n.html#how-social-authentication-works

**Comment by advance512** [comment]
Great answer. Thank you!
